export const ADD_VIDEO_TO_STASH = " ADD_VIDEO_TO_STASH";
export const REMOVE_VIDEO_FROM_STASH = "REMOVE_VIDEO_FROM_STASH";
export const UPDATE_STASH_VIDEO = "UPDATE_STASH_VIDEO";
export const UPDATE_VIDEO = "UPDATE_VIDEO";
